apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-qnet
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0070-tenant/tkrw-pr712-0075-0070-app/devfile-sample-qnet@sha256:c7615e37f5be239e9d9bf24a3259e7f669fb0a3db52d783cdbfcf396281df785
        name: my-nodejs
        resources: {}
status: {}
